In [1]:
# ==============================
# Setup de ambiente do notebook
# ==============================
import sys
from pathlib import Path
import pandas as pd

In [2]:
NOTEBOOK_DIR = Path().resolve()
PROJECT_ROOT = NOTEBOOK_DIR.parent

NOTEBOOK_DIR, PROJECT_ROOT

(WindowsPath('C:/Users/gfasg/OneDrive/Área de Trabalho/Projeto Dengue/dengue-territorio-e-condicoes-urbanas-recife/notebooks'),
 WindowsPath('C:/Users/gfasg/OneDrive/Área de Trabalho/Projeto Dengue/dengue-territorio-e-condicoes-urbanas-recife'))

In [3]:
(PROJECT_ROOT / "data").exists(), list((PROJECT_ROOT / "data").iterdir())

(True,
 [WindowsPath('C:/Users/gfasg/OneDrive/Área de Trabalho/Projeto Dengue/dengue-territorio-e-condicoes-urbanas-recife/data/analytics'),
  WindowsPath('C:/Users/gfasg/OneDrive/Área de Trabalho/Projeto Dengue/dengue-territorio-e-condicoes-urbanas-recife/data/processed'),
  WindowsPath('C:/Users/gfasg/OneDrive/Área de Trabalho/Projeto Dengue/dengue-territorio-e-condicoes-urbanas-recife/data/raw')])

In [4]:
(PROJECT_ROOT / "data" / "raw").exists(), list((PROJECT_ROOT / "data" / "raw").iterdir())

(True,
 [WindowsPath('C:/Users/gfasg/OneDrive/Área de Trabalho/Projeto Dengue/dengue-territorio-e-condicoes-urbanas-recife/data/raw/chikungunya'),
  WindowsPath('C:/Users/gfasg/OneDrive/Área de Trabalho/Projeto Dengue/dengue-territorio-e-condicoes-urbanas-recife/data/raw/demografia'),
  WindowsPath('C:/Users/gfasg/OneDrive/Área de Trabalho/Projeto Dengue/dengue-territorio-e-condicoes-urbanas-recife/data/raw/dengue'),
  WindowsPath('C:/Users/gfasg/OneDrive/Área de Trabalho/Projeto Dengue/dengue-territorio-e-condicoes-urbanas-recife/data/raw/metadados'),
  WindowsPath('C:/Users/gfasg/OneDrive/Área de Trabalho/Projeto Dengue/dengue-territorio-e-condicoes-urbanas-recife/data/raw/saneamento'),
  WindowsPath('C:/Users/gfasg/OneDrive/Área de Trabalho/Projeto Dengue/dengue-territorio-e-condicoes-urbanas-recife/data/raw/tabelas_auxiliares'),
  WindowsPath('C:/Users/gfasg/OneDrive/Área de Trabalho/Projeto Dengue/dengue-territorio-e-condicoes-urbanas-recife/data/raw/zika')])

In [5]:
for agravo in ["dengue", "zika", "chikungunya"]:
    path = PROJECT_ROOT / "data" / "raw" / agravo
    print(agravo, "-> existe?", path.exists())

dengue -> existe? True
zika -> existe? True
chikungunya -> existe? True

In [6]:
dengue_path = PROJECT_ROOT / "data" / "raw" / "dengue"
list(dengue_path.glob("*.csv"))

[WindowsPath('C:/Users/gfasg/OneDrive/Área de Trabalho/Projeto Dengue/dengue-territorio-e-condicoes-urbanas-recife/data/raw/dengue/dengon-2021-ok.csv'),
 WindowsPath('C:/Users/gfasg/OneDrive/Área de Trabalho/Projeto Dengue/dengue-territorio-e-condicoes-urbanas-recife/data/raw/dengue/dengon-2022.csv'),
 WindowsPath('C:/Users/gfasg/OneDrive/Área de Trabalho/Projeto Dengue/dengue-territorio-e-condicoes-urbanas-recife/data/raw/dengue/dengon-2023-ok-1.csv'),
 WindowsPath('C:/Users/gfasg/OneDrive/Área de Trabalho/Projeto Dengue/dengue-territorio-e-condicoes-urbanas-recife/data/raw/dengue/dengon-2024.csv'),
 WindowsPath('C:/Users/gfasg/OneDrive/Área de Trabalho/Projeto Dengue/dengue-territorio-e-condicoes-urbanas-recife/data/raw/dengue/dengon2020_recife.csv')]

In [7]:
import sys

sys.path.insert(0, str(PROJECT_ROOT))
sys.path[:3]

['C:\\Users\\gfasg\\OneDrive\\Área de Trabalho\\Projeto Dengue\\dengue-territorio-e-condicoes-urbanas-recife',
 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\python311.zip',
 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\DLLs']

In [8]:
from src.transform.join_tables import join_agravo_years

join_agravo_years

In [13]:
df_dengue = join_agravo_years(
    agravo="dengue",
    base_path=PROJECT_ROOT / "data" / "raw"
)

df_dengue.shape
df_dengue.head()

,ï»¿NU_NOTIFIC,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,...,co_pais_infeccao,co_municipio_infeccao,co_distrito_infeccao,co_bairro_infeccao,no_bairro_infeccao,tp_classificacao_final,tp_criterio_confirmacao,st_doenca_trabalho,tp_evolucao_caso,dt_encerramento
0,3730655.0,2.0,A90,01/01/2021,202053.0,2021.0,26.0,261160.0,1497.0,671.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3730656.0,2.0,A90,01/01/2021,202053.0,2021.0,26.0,261160.0,1497.0,671.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3730652.0,2.0,A90,01/01/2021,202053.0,2021.0,26.0,261160.0,1497.0,671.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3730657.0,2.0,A90,01/01/2021,202053.0,2021.0,26.0,261160.0,1497.0,671.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4197902.0,2.0,A90,01/01/2021,202053.0,2021.0,26.0,261160.0,1497.0,590.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df_zika = join_agravo_years(
    agravo="zika",
    base_path=PROJECT_ROOT / "data" / "raw"
)

df_zika.shape
df_zika.head()

,NU_NOTIFIC,TP_NOT,ID_AGRAVO,CS_SUSPEIT,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,...,co_uf_infeccao,co_pais_infeccao,co_municipio_infeccao,co_distrito_infeccao,co_bairro_infeccao,no_bairro_infeccao,st_doenca_trabalho,tp_evolucao_caso,dt_obito,dt_encerra
0,3716012.0,2.0,A928,NaN,2021-01-11,202102.0,2021.0,26.0,261160.0,1497.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3725134.0,2.0,A928,NaN,2021-01-27,202104.0,2021.0,26.0,261160.0,1497.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3762467.0,2.0,A928,NaN,2021-02-04,202105.0,2021.0,26.0,261160.0,1497.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3802872.0,2.0,A928,NaN,2021-02-10,202106.0,2021.0,26.0,260290.0,1497.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3908667.0,2.0,A928,NaN,2021-04-28,202117.0,2021.0,26.0,261160.0,1497.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df_chik = join_agravo_years(
    agravo="chikungunya",
    base_path=PROJECT_ROOT / "data" / "raw"
)

df_chik.shape
df_chik.head()

,ï»¿NU_NOTIFIC,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,...,petequias,hematura,sangram,laco_n,plasmatico,evidencia,plaq_menor,con_fhd,complica,NU_NOTIFIC
0,3730663.0,2.0,A92.0,01/01/2021,202053.0,2021.0,26.0,261160.0,1497.0,671.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3730659.0,2.0,A92.0,01/01/2021,202053.0,2021.0,26.0,261160.0,1497.0,671.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3730662.0,2.0,A92.0,01/01/2021,202053.0,2021.0,26.0,261160.0,1497.0,671.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3730664.0,2.0,A92.0,02/01/2021,202053.0,2021.0,26.0,261160.0,1497.0,671.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3730665.0,2.0,A92.0,02/01/2021,202053.0,2021.0,26.0,261160.0,1497.0,671.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN